name: Deploy ASP.NET Core to Azure Web Application

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

env:
  AZURE_WEBAPP_NAME: WebApp1794
  AZURE_WEBAPP_PATH: '.'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login via Azure CLI
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PATH }}/myapp'
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PATH }}/myapp'
